modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="crushingwheelrecipeselector"
version="1.0.1"
displayName="Crushing Wheel Recipe Selector"
authors="EnormeBoze"
description='''
Allows you to choose which output you want from Create's crushing wheels when multiple mods add conflicting recipes.
'''

[[dependencies.crushingwheelrecipeselector]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.crushingwheelrecipeselector]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.crushingwheelrecipeselector]]
modId="create"
mandatory=true
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="crushingwheelrecipeselector.mixins.json"